version: '2'
services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    ports:
      - "6479:6379"
  # Gitlab - GitLab is open source software to collaborate on code
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
      - ./postgresql/data:/var/lib/postgresql:Z
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm
    ports: 
      - "5432:5432"
  gitlab:
    image: sameersbn/gitlab:9.2.2
    ports: 
      - "8443:443"
      - "8080:80"
      - "2222:22"
    volumes:
      - ./gitlab/data:/home/git/data:Z
      - ./gitlab/logs:/var/log/gitlab
    links:
      - redis
      - postgresql
    env_file: 
      - .env